In [2]:
import pandas as pd
import json
from pathlib import Path

Fiona:
- 1 - 2 paragraph summary statistics (number of rows, number of categories to show that we have enough diversity in the data set to handle ad hoc querying, show that we have images, number of patterns per skill level, talk about how we can merge everything to create a long description )

Ying:
- figures and the second figure
- webscraping

In [9]:
data_folder = Path("data/crochet_pattern_by_project")

dfs = []

for file in data_folder.glob("*.json"):
    with open(file, "r") as f:
        data = json.load(f)
    df = pd.DataFrame(data)
    df["file_name"] = file.name
    dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)
combined_df.head()

,pattern_name,materials,skill_type,skill_level,abbreviations,measurements,gauge,instructions,id,project_type,source,image_link,file_name,notes,finishing,remaining_panels,additional_instructions
0,Cross-hatched Cowl & Beanie,[RED HEART® Reflective™: 3 balls of 8884 Peaco...,crochet,easy,"[A, B = color A, B, ch = chain, hdc = half dou...",Cowl measures 5” (12.5 cm) wide x 60” (152.5 c...,COWL GAUGE: 10 sts and 9 rows = 4” (10 cm) in ...,"COWL\nWith A, Ch 150, and without twisting ch;...",RHC0116-019549M,Hats,./input_file/Hats/RHC0116-019549M.pdf,https://www.yarnspirations.com/cdn/shop/produc...,Hats.json,NaN,NaN,NaN,NaN
1,Crochet Letter Hats,"[1 skein each 1801 Navy and 1502 Iced Aqua, Su...",crochet,easy,"[ch = chain(s), hdc = half double crochet, sc ...","Hat measures 18 (20, 22)"" [45.5 (51, 56) cm] c...","12 sts = 4"" (10 cm); 9 rows = 4"" (10 cm). CHEC...",HAT (make 1 with each color)\nCh 4; join with ...,RHC0316-017277M,Hats,./input_file/Hats/RHC0316-017277M.pdf,https://www.yarnspirations.com/cdn/shop/produc...,Hats.json,NaN,NaN,NaN,NaN
2,Daisy Chain Border CardiGan & Hat,[Patons® Beehive Baby sport (100 g/3.5 oz; 328...,crochet,intermediate,"[approx = Approximate(ly)., beg = Beginning., ...","To fit chest measurement 6 mos 17” [43 cm], 12...",5½ clusters and 10 rows = 4” [10 cm] in Basic ...,The instructions are written for smallest size...,PAC0216-000028M,Hats,./input_file/Hats/PAC0216-000028M.pdf,https://www.yarnspirations.com/cdn/shop/produc...,Hats.json,NaN,NaN,NaN,NaN
3,Classic Crochet Beret,"[Bernat® Satin (100 g/3.5 oz; 182 m/200 yds), ...",crochet,intermediate,"[Ch = Chain., Cont = Continue(ity)., Inc = inc...",One size to fit average lady’s head.,15 sc and 16 rows = 4” [10 cm].,Ch 6. Join with sl st to first ch to form a ri...,BRC0116-000013M,Hats,./input_file/Hats/BRC0116-000013M.pdf,https://www.yarnspirations.com/cdn/shop/produc...,Hats.json,NaN,NaN,NaN,NaN
4,Buttoned Cloche Hat,"[RED HEART® Medley™: 2 balls 954 Eclectic, Sus...",crochet,easy,"[ch = chain(s), hdc = half double crochet, st(...",Hat measures 24” (61 cm) circumference at brim.,11 hdc = 4” (10 cm).,HAT\nCh 5; join with slip st in first ch to fo...,RHC0116-018071M,Hats,./input_file/Hats/RHC0116-018071M.pdf,https://www.yarnspirations.com/cdn/shop/produc...,Hats.json,NaN,NaN,NaN,NaN

In [10]:
combined_df.to_csv("combined_crochet_patterns.csv", index=False)

In [ ]:
print (combined_df.shape)
combined_df.groupby("file_name").count()

,pattern_name,materials,skill_type,skill_level,abbreviations,measurements,gauge,instructions,id,project_type,source,image_link,notes,finishing,remaining_panels,additional_instructions
file_name,,,,,,,,,,,,,,,,
Afghans_Blankets.json,1591,1591,1591,1591,1591,1591,1591,1591,1591,1591,1591,1562,1,1,1,0
Amigurumi+%26+Toys.json,286,286,286,286,286,286,286,286,286,286,286,282,0,0,0,0
Appliqués.json,42,42,42,42,42,42,42,42,42,42,42,41,0,0,0,0
Aprons.json,11,11,11,11,11,11,11,11,11,11,11,11,0,0,0,0
Bags+%26+Purses.json,249,249,249,249,249,249,249,249,249,249,249,248,0,0,0,0
Baskets.json,118,118,118,118,118,118,118,118,118,118,118,113,0,0,0,0
Bibs.json,7,7,7,7,7,7,7,7,7,7,7,7,0,0,0,0
Booties.json,24,24,24,24,24,24,24,24,24,24,24,24,0,0,0,0
Bunting_Bags.json,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,0
Buntings+%26+Garlands.json,36,36,36,36,36,36,36,36,36,36,36,36,0,0,0,0
Capes+%26+Ponchos.json,85,85,85,85,85,85,85,85,85,85,85,81,0,0,0,0
Coasters.json,26,26,26,26,26,26,26,26,26,26,26,25,0,0,0,0
Costumes.json,59,59,59,59,59,59,59,59,59,59,59,58,0,0,0,0
Cowls.json,154,154,154,154,154,154,154,154,154,154,154,153,0,0,0,0
Cozies.json,61,61,61,61,61,61,61,61,61,61,61,61,0,0,0,0
Cross+stitch+%26+Embroidery.json,6,6,6,6,6,6,6,6,6,6,6,6,0,0,0,0
Décor.json,231,231,231,231,231,231,231,231,231,231,231,230,0,0,0,0
Dishcloths.json,222,222,222,222,222,222,222,222,222,222,222,222,0,0,0,0
Dresses.json,34,34,34,34,34,34,34,34,34,34,34,34,0,0,0,0
Gift+Wrapping.json,10,10,10,10,10,10,10,10,10,10,10,10,0,0,0,0
Gloves+%26+Mittens.json,64,64,64,64,64,64,64,64,64,64,64,64,0,0,0,0
Hair_Accessories.json,5,5,5,5,5,5,5,5,5,5,5,5,0,0,0,0
Hats.json,424,424,424,424,424,424,424,424,424,424,424,421,0,0,0,0
Headbands.json,38,38,38,38,38,38,38,38,38,38,38,37,0,0,0,0
Jackets.json,31,31,31,31,31,31,31,31,31,31,31,31,0,0,0,0
Jewelry.json,55,55,55,55,55,55,55,55,55,55,55,54,0,0,0,0
Onesies+%26+Rompers.json,5,5,5,5,5,5,5,5,5,5,5,5,0,0,0,0
Organizers+%26+Jars.json,34,34,34,34,34,34,34,34,34,34,34,34,0,0,0,0
Ornaments.json,35,35,35,35,35,35,35,35,35,35,35,35,0,0,0,0
Other+Accessories.json,99,99,99,99,99,99,99,99,99,99,99,98,0,0,0,0
Other+Pet+Accessories.json,6,6,6,6,6,6,6,6,6,6,6,6,0,0,0,0
Pants.json,11,11,11,11,11,11,11,11,11,11,11,11,0,0,0,0
Pet+Bed.json,16,16,16,16,16,16,16,16,16,16,16,15,0,0,0,0
Pillows+%26+Poufs.json,293,293,293,293,293,293,293,293,293,293,293,292,0,0,0,0
Placemats+%26+Table+Décor.json,100,100,100,100,100,100,100,100,100,100,100,97,0,0,0,0
Plant+Décor.json,40,40,40,40,40,40,40,40,40,40,40,38,0,0,0,0
Rugs.json,53,53,52,52,52,52,52,52,53,53,53,52,0,0,0,0
Scarves.json,304,304,304,304,304,304,304,304,304,304,304,299,0,0,0,0
Sets.json,111,111,111,111,111,111,111,111,111,111,111,107,0,0,0,0
Shawls+%26+Wraps.json,330,330,330,330,330,330,330,330,330,330,330,328,0,0,0,0
Shorts.json,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,0
Skirts.json,21,21,21,21,21,21,21,21,21,21,21,21,0,0,0,0
Slippers.json,36,36,36,36,36,36,36,36,36,36,36,36,0,0,0,0
Socks.json,30,30,30,30,30,30,30,30,30,30,30,30,0,0,0,0
Stockings.json,7,7,7,7,7,7,7,7,7,7,7,7,0,0,0,0
Super+Scarves.json,13,13,13,13,13,13,13,13,13,13,13,13,0,0,0,0
Sweaters+%26+Cardigans.json,357,357,357,357,357,357,357,357,357,357,357,357,0,0,0,1
Tank+Tops.json,33,33,33,33,33,33,33,33,33,33,33,33,0,0,0,0
Tech+Accessories.json,13,13,13,13,13,13,13,13,13,13,13,13,0,0,0,0
Tops.json,66,66,66,66,66,66,66,66,66,66,66,65,0,0,0,0
Tunics.json,29,29,29,29,29,29,29,29,29,29,29,29,0,0,0,0
Vests.json,64,64,64,64,64,64,64,64,64,64,64,63,0,0,0,0
Wall_Hangings.json,53,53,53,53,53,53,53,53,53,53,53,53,0,0,0,0
Washcloths+%26+Mitts.json,28,28,28,28,28,28,28,28,28,28,28,28,0,0,0,0
Wreaths.json,23,23,23,23,23,23,23,23,23,23,23,23,0,0,0,0

In [13]:
combined_df.isna().sum()

pattern_name                  0
materials                     0
skill_type                    1
skill_level                   1
abbreviations                 1
measurements                  1
gauge                         1
instructions                  1
id                            0
project_type                  0
source                        0
image_link                   75
file_name                     0
notes                      6084
finishing                  6084
remaining_panels           6084
additional_instructions    6084
dtype: int64

In [ ]:
combined_df['pattern_name'] + " - " + combined_df['skill_type']

In [16]:
combined_df.loc[0, 'instructions']

'COWL\nWith A, Ch 150, and without twisting ch; join with a slip st in first ch.\nRound 1 (right side): Ch 2 (counts as hdc here and throughout), hdc in each ch around; join with a slip st in top of beginning ch-2—150 hdc.\nRound 2: Ch 3 (counts as dc here and throughout), (dc, ch 2, sc) in first st, *skip next 2 sts, (2 dc, ch 2, sc) in next hdc; repeat from * around, skip last 2 sts; join with a slip st in top of beginning ch-3—50 shells.\nRound 3: Slip st in next dc, ch 1, (sc, ch 2, 2 dc) in each ch-2 sp around; join with a slip st in first sc—50 shells.\nRound 4: Slip st in next ch-2 space, ch 3, (dc, ch 2, sc) in same ch-2 space, (2 dc, ch 2, sc) in each ch-2 space around; join with a slip st in top of beginning ch-3, change to B—50 shells. Fasten off A.\nRounds 5-10: Rep Rounds 3-4, working in the following color sequence: *1 round B, 2 rounds A; repeat from * once.\nRound 11: Ch 2, *2 hdc in next ch-2 space**, hdc in space between next sc and next dc; repeat from * around, ending last repeat at **; join with a slip st in top of beginning ch-2. Fasten off. Weave in ends.\nBEANIE\nWith A, make an adjustable ring or ch 3; join with a slip st in first ch.\nRound 1: Ch 3 (counts as dc here and throughout), 11 dc in ring; join with a slip st in top of beginning ch-3—12 dc.\nRound 2: Ch 3, dc in first st, 2 dc in each st around—24 dc.\nRound 7: Slip st in next ch-2 sp, ch 3, (dc, ch 2, sc) in same ch-2 space, (2 dc, ch 2, sc) in each ch-2 space around; join with a slip st in top of beginning ch-3—14 shells.\nRounds 8-13: Repeat Rounds 6-7 (3 times), working in the following color sequence: 1 more round A; 1 round B; 2 rounds A; 1 round B; 1 round A.\nRound 14: Slip st in next dc, ch 1, *2 sc in next ch-2 space**, sc in space between next sc and next dc; repeat from * around, ending last repeat at **; join with a slip st in top of beginning ch-2. Fasten off. Weave in ends.'