In [93]:
import pandas as pd
import os

In [94]:
all_free_df = pd.read_csv("../data/all_free_crochet_patterns.csv")
cols = ['title', 'description', 'skill_level', 'Crochet Hook', 'Yarn Weight', 'Finished Size']

all_free_df['final_description'] = (
    all_free_df[cols]
    .fillna('')
    .agg(' '.join, axis=1)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)
all_free_df.head()

all_free_df.rename(columns={'Crochet Hook': 'crochet_hook', 
'Yarn Weight': 'yarn_weight',
'Crochet Gauge': 'crochet_gauge',
'Finished Size': 'finished_size'}, inplace=True)
all_free_df.head()
# print(all_free_df.iloc[0,1])

,title,description,skill_level,crochet_hook,yarn_weight,finished_size,img_url,local_path,pattern_link,crochet_gauge,Notes,final_description
0,Quick n' Cozy Crochet Afghan,The Quick n' Cozy Crochet Afghan is the ultima...,Beginner,P/16 or 11.5 mm hook,(6) Super Bulky/Super Chunky (4-11 stitches fo...,"44 x 55""",https://irepo.primecp.com/2015/06/225420/Quick...,Quick_n_Cozy_Crochet_Afghan.jpg,https://www.allfreecrochet.com/Crochet-Afghan-...,NaN,NaN,Quick n' Cozy Crochet Afghan The Quick n' Cozy...
1,World's Easiest Afghan,If you've been searching for easy afghan patte...,Beginner,H/8 or 5 mm hook,(4) Medium Weight/Worsted Weight and Aran (16-...,Measurement: 48 x 60”,https://irepo.primecp.com/2014/12/204013/World...,Worlds_Easiest_Afghan.jpg,https://www.allfreecrochet.com/Crochet-Afghan-...,"13 sc and 14 rows = 4"" (10cm)",NaN,World's Easiest Afghan If you've been searchin...
2,Ribbed Fingerless Gloves,"""These crochet ribbed fingerless gloves are ma...",Beginner,4.5 mm hook,(4) Medium Weight/Worsted Weight and Aran (16-...,NaN,https://irepo.primecp.com/2026/03/609601/17728...,Ribbed_Fingerless_Gloves.jpg,https://www.allfreecrochet.com/Gloves-and-Mitt...,NaN,NaN,"Ribbed Fingerless Gloves ""These crochet ribbed..."
3,Chunky Adult Slippers,Learn how to crochet an adorable pair of Chunk...,Beginner,M/13 or 9 mm hook,(4) Medium Weight/Worsted Weight and Aran (16-...,NaN,https://irepo.primecp.com/2020/11/471382/Chunk...,Chunky_Adult_Slippers.jpg,https://www.allfreecrochet.com/Socks-and-Slipp...,Gauge 2 sc = 1 inch,NaN,Chunky Adult Slippers Learn how to crochet an ...
4,Quick Little Bag,"""This Quick Little Bag is just that, and it ca...",Beginner,I/9 or 5.5 mm hook,(4) Medium Weight/Worsted Weight and Aran (16-...,5 inch square,https://irepo.primecp.com/2015/09/238794/Quick...,Quick_Little_Bag.jpg,https://www.allfreecrochet.com/Crochet-Bag-Pat...,NaN,NaN,"Quick Little Bag ""This Quick Little Bag is jus..."

In [95]:
crochet_df = pd.read_csv("../data/crochet_crochet_patterns.csv")

# dropping this, has all nans
crochet_df = crochet_df.drop(columns=['Yarn Line', 'Yardage'])
description_col = crochet_df.columns[:-3]
print(description_col)

crochet_df['final_description'] = (
    crochet_df[description_col]
    .fillna('')
    .agg(' '.join, axis=1)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

crochet_df.rename(columns = {'Fiber Type': 'fiber_type', 'Pattern Type': 'pattern_type', 'Yarn Weight': 'yarn_weight', 
'Sizes Included': 'finished_size', 'Difficulty': 'skill_level', 'Needle / Hook Sizes': 'crochet_hook'}, 
inplace = True)

crochet_df.head()

Index(['title', 'description', 'Pattern Type', 'Difficulty', 'Sizes Included',
       'Yarn Weight', 'Fiber Type', 'Needle / Hook Sizes'],
      dtype='object')

,title,description,pattern_type,skill_level,finished_size,yarn_weight,fiber_type,crochet_hook,image_url,local_path,pattern_link,final_description
0,Wavy Chevron Dishcloth,Save when you buy a project bundle! Striped or...,Crochet,Beginner,"Bright Colorway, Cabin Colorway, Candy Colorway",Worsted,Cotton,Size G (4.0mm) crochet hook,https://d2q9kw5vp0we94.cloudfront.net/i/_/big/...,Wavy_Chevron_Dishclothby_Jenny_Konopinski.jpg,https://www.crochet.com/wavy-chevron-dishcloth...,Wavy Chevron Dishcloth Save when you buy a pro...
1,Filet Crochet Market Bag,Make a stunning market bag for trips to the fa...,Crochet,Intermediate,"27"" circumference, 15"" long",DK,Cotton,Size G (4.0mm) Crochet hook,https://d2q9kw5vp0we94.cloudfront.net/i/_/big/...,Filet_Crochet_Market_Bagby_Sara_Dudek.jpg,https://www.crochet.com/filet-crochet-market-b...,Filet Crochet Market Bag Make a stunning marke...
2,Good Earth Blanket,Get cozy in color with a striped crochet blank...,Crochet,Beginner,"35.75 x 48"" - spring picnic, 48.25 x 60"" - spr...",Worsted,Acrylic,US 7 (4.5mm) crochet hook,https://d2q9kw5vp0we94.cloudfront.net/i/_/big/...,Good_Earth_Blanketby_Pattern_Hut.jpg,https://www.crochet.com/good-earth-blanket/p/N...,Good Earth Blanket Get cozy in color with a st...
3,Aberdeen Pullover,Bold and modern the geometric mosaic pattern o...,Crochet,Intermediate,"38.5"" finished chest, 42.75"" finished chest, 4...",Worsted,Acrylic,H/5.0mm & I/5.5mm crochet hooks,https://d2q9kw5vp0we94.cloudfront.net/i/_/big/...,Aberdeen_Pulloverby_Moon_Elderidge.jpg,https://www.crochet.com/aberdeen-pullover/p/56291,Aberdeen Pullover Bold and modern the geometri...
4,Adventure Time Blanket,Playful vehicles set off for adventure on this...,Crochet,Intermediate,"24"" Wide x 36"" Long",Fingering,Cotton,US D/3 (3.25mm) Crochet hook,https://d2q9kw5vp0we94.cloudfront.net/i/_/big/...,Adventure_Time_Blanketby_Amy_Polcyn_Niezur.jpg,https://www.crochet.com/adventure-time-blanket...,Adventure Time Blanket Playful vehicles set of...

In [96]:
herrschners_df = pd.read_csv("../data/herrschners_crochet_patterns.csv")
herrschners_df = herrschners_df.drop(columns=['sku','upc'])
herrschners_df.head()
herrschners_df.rename(columns = {'product_link': 'pattern_link', 'skill': 'pattern_type', 
'difficulty': 'skill_level'}, inplace = True)
exclude_cols = ['pattern_link', 'review_count', 'image_url', 'local_path', 'star_rating', 'thread_size']
description_col = [col for col in herrschners_df.columns if col not in exclude_cols]
print(description_col)

herrschners_df['final_description'] = (
    herrschners_df[description_col]
    .fillna('')
    .agg(' '.join, axis=1)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)
herrschners_df.head()

['title', 'project_type', 'pattern_type', 'skill_level', 'merged_info', 'description', 'occasion', 'season', 'theme', 'fiber_content', 'yarn_weight']

,pattern_link,title,project_type,pattern_type,skill_level,merged_info,description,review_count,star_rating,image_url,local_path,occasion,season,theme,fiber_content,yarn_weight,thread_size,final_description
0,https://herrschners.com/herrschners-modern-mes...,Modern Mesa Pillow,Pillow,Knit,Beginner,F01731 Pillow Knit Easy,Create a cozy sitting area filled with hand-st...,0,0,https://cdn11.bigcommerce.com/s-wgzqwlngdf/ima...,Herrschners_Modern_Mesa_Pillow.jpg,NaN,NaN,NaN,NaN,NaN,NaN,Modern Mesa Pillow Pillow Knit Beginner F01731...
1,https://herrschners.com/herrschners-sunrise-st...,Sunrise Stroll Tote,Tote,Crochet,Beginner,F01730 Tote Crochet Easy,Accessorize in style with this textured two-to...,0,0,https://cdn11.bigcommerce.com/s-wgzqwlngdf/ima...,Herrschners_Sunrise_Stroll_Tote.jpg,NaN,NaN,NaN,NaN,NaN,NaN,Sunrise Stroll Tote Tote Crochet Beginner F017...
2,https://herrschners.com/village-yarn-blue-burs...,Village Yarn Blue Burst Pot Holders,Pot Holders,Crochet,Beginner,F01729 Pot Holders Crochet Easy,Brighten your kitchen with a splash of color! ...,0,0,https://cdn11.bigcommerce.com/s-wgzqwlngdf/ima...,Village_Yarn_Blue_Burst_Pot_Holders.jpg,NaN,NaN,NaN,NaN,NaN,NaN,Village Yarn Blue Burst Pot Holders Pot Holder...
3,https://herrschners.com/willow-yarns-garden-so...,Willow Yarns Garden Song Shawlette,Shawl,Knit,Beginner,F01728 Shawl Knit Easy,Be ready for backyard garden parties with this...,0,0,https://cdn11.bigcommerce.com/s-wgzqwlngdf/ima...,Willow_Yarns_Garden_Song_Shawlette.jpg,NaN,NaN,NaN,NaN,NaN,NaN,Willow Yarns Garden Song Shawlette Shawl Knit ...
4,https://herrschners.com/herrschners-english-ga...,English Garden Doily,Doily,Crochet,Beginner,F01727 Doily Crochet Easy,No green thumb is needed to grow a garden of t...,0,0,https://cdn11.bigcommerce.com/s-wgzqwlngdf/ima...,Herrschners_English_Garden_Doily.jpg,NaN,NaN,NaN,NaN,NaN,NaN,English Garden Doily Doily Crochet Beginner F0...

In [97]:
lovecrafts_df = pd.read_csv("../data/lovecrafts_crochet_patterns.csv")
lovecrafts_df = lovecrafts_df.drop(columns = ['format', 'merged_info',
'techniques_and_construction', 'needles_required', 'crochet_thread_size'])
lovecrafts_df.head()

lovecrafts_df.rename(columns = {'product_link': 'pattern_link', 'craft': 'pattern_type'}, inplace = True)
exclude_cols = ['pattern_link', 'image_url', 'local_path']

lovecrafts_df['pages'] = lovecrafts_df['pages'].astype(str) + 'pages'
lovecrafts_df['number_of_patterns'] = lovecrafts_df['number_of_patterns'].astype(str) + 'patterns'

description_col = [col for col in lovecrafts_df.columns if col not in exclude_cols]
print(description_col)

lovecrafts_df['final_description'] = (
    lovecrafts_df[description_col]
    .fillna('')
    .agg(' '.join, axis=1)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)
lovecrafts_df.head()

['title', 'brand', 'pattern_type', 'designer', 'language', 'notes', 'number_of_patterns', 'pages', 'skill_level', 'yarn_weight', 'description', 'featured_product', 'crochet_hooks', 'finished_size', 'craft_category']

,title,brand,pattern_type,designer,language,notes,number_of_patterns,pages,skill_level,yarn_weight,description,image_url,local_path,pattern_link,featured_product,crochet_hooks,finished_size,craft_category,final_description
0,Jellyfish Babies,Independent Designer,Crochet,Jade Gauthier-Boutin,"English, French",• Two 6 mm safety eyes,1.0patterns,14.0pages,Beginner,Worsted,"With this pattern, you will be able to make as...",https://isv.prod.lovecrafts.co/v1/images/87236...,Jellyfish_Babies.jpg,https://www.lovecrafts.com/en-us/p/jellyfish-b...,NaN,NaN,NaN,NaN,Jellyfish Babies Independent Designer Crochet ...
1,Sakura Market Bag,Independent Designer,Crochet,K.A.M.E. Crochet,"Dutch, English, French, German",NaN,1.0patterns,33.0pages,Intermediate,DK | Light Worsted,"NEW UPDATED VERSION CONTAINS DUTCH, FRENCH, GE...",https://isv.prod.lovecrafts.co/v1/images/cd77c...,Sakura_Market_Bag.jpg,https://www.lovecrafts.com/en-us/p/sakura-mark...,Paintbox Yarns Cotton DK,NaN,NaN,NaN,Sakura Market Bag Independent Designer Crochet...
2,Easy Peasy Crochet Baby Blanket in Caron One P...,Caron,Crochet,NaN,English,NaN,1.0patterns,2.0pages,Beginner,AranSee Worsted Knitting PatternsSee Aran Croc...,Learn how to crochet with our beginners guide!,https://isv.prod.lovecrafts.co/v1/images/8a9cf...,Easy_Peasy_Crochet_Baby_Blanket_in_Caron_One_P...,https://www.lovecrafts.com/en-us/p/easy-peasy-...,Caron One Pound,6.00mm (J),Blanket: 40in square,NaN,Easy Peasy Crochet Baby Blanket in Caron One P...
3,Baby Turtles,Independent Designer,Crochet,Jade Gauthier-Boutin,"English, French","• Two 6 mm safety eyes or buttons, beads, felt...",1.0patterns,12.0pages,Beginner,Worsted,"SKILLS REQUIRED Crocheting in spiral, magic ri...",https://isv.prod.lovecrafts.co/v1/images/c5cdb...,Baby_Turtles.jpg,https://www.lovecrafts.com/en-us/p/baby-turtle...,NaN,NaN,NaN,NaN,Baby Turtles Independent Designer Crochet Jade...
4,Squishy Baby Octopus,Independent Designer,Crochet,Jade Gauthier-Boutin,"English, French",Two 12 mm safety eyes,1.0patterns,6.0pages,Beginner,Super Bulky,"With this pattern, you will be able to make as...",https://isv.prod.lovecrafts.co/v1/images/95d72...,Squishy_Baby_Octopus.jpg,https://www.lovecrafts.com/en-us/p/squishy-bab...,NaN,NaN,NaN,NaN,Squishy Baby Octopus Independent Designer Croc...

In [98]:
herrschners_df['description'] = herrschners_df['description'].str.split("Skill Level").str[0].str.strip()

In [99]:
lovecrafts_df['title'].unique()

array(['Jellyfish Babies', 'Sakura Market Bag',
       'Easy Peasy Crochet Baby Blanket in Caron One Pound - Downloadable PDF',
       ..., 'Becoming Basket', 'How to do the crocodile st',
       'Peaks and Valley Throw in Red Heart Super Saver Economy Solids - LW2046'],
      shape=(1838,), dtype=object)

In [113]:
lovecrafts_df['title'] = lovecrafts_df['title'].str.split(" - Downloadable PDF").str[0].str.strip()

In [114]:
lovecrafts_df['title'].unique()

array(['Jellyfish Babies', 'Sakura Market Bag',
       'Easy Peasy Crochet Baby Blanket in Caron One Pound', ...,
       'Becoming Basket', 'How to do the crocodile st',
       'Peaks and Valley Throw in Red Heart Super Saver Economy Solids - LW2046'],
      shape=(1838,), dtype=object)

In [115]:
lovecrafts_df.isna().sum()

title                   11
brand                   11
pattern_type            11
designer               605
language                13
notes                 1400
number_of_patterns       0
pages                    0
skill_level            423
yarn_weight            403
description             11
image_url               11
local_path              12
pattern_link             0
featured_product       882
crochet_hooks          989
finished_size         1284
craft_category        1849
final_description        0
dtype: int64

In [116]:
features = ['title', 'description', 'final_description', 'skill_level', 'pattern_link', 'local_path']

In [117]:
combined_df = pd.concat(
    [
        all_free_df[features],
        crochet_df[features],
        lovecrafts_df[features],
        herrschners_df[features]
    ],
    axis=0,
    ignore_index=True
)

combined_df.shape

(2778, 6)

In [118]:
combined_df = combined_df[~combined_df[["title", "pattern_link", "local_path"]].isna().any(axis=1)]

In [119]:
combined_df.shape

(2766, 6)

In [120]:
combined_df.head()

,title,description,final_description,skill_level,pattern_link,local_path
0,Quick n' Cozy Crochet Afghan,The Quick n' Cozy Crochet Afghan is the ultima...,Quick n' Cozy Crochet Afghan The Quick n' Cozy...,Beginner,https://www.allfreecrochet.com/Crochet-Afghan-...,Quick_n_Cozy_Crochet_Afghan.jpg
1,World's Easiest Afghan,If you've been searching for easy afghan patte...,World's Easiest Afghan If you've been searchin...,Beginner,https://www.allfreecrochet.com/Crochet-Afghan-...,Worlds_Easiest_Afghan.jpg
2,Ribbed Fingerless Gloves,"""These crochet ribbed fingerless gloves are ma...","Ribbed Fingerless Gloves ""These crochet ribbed...",Beginner,https://www.allfreecrochet.com/Gloves-and-Mitt...,Ribbed_Fingerless_Gloves.jpg
3,Chunky Adult Slippers,Learn how to crochet an adorable pair of Chunk...,Chunky Adult Slippers Learn how to crochet an ...,Beginner,https://www.allfreecrochet.com/Socks-and-Slipp...,Chunky_Adult_Slippers.jpg
4,Quick Little Bag,"""This Quick Little Bag is just that, and it ca...","Quick Little Bag ""This Quick Little Bag is jus...",Beginner,https://www.allfreecrochet.com/Crochet-Bag-Pat...,Quick_Little_Bag.jpg

In [121]:
combined_df["local_path"] = combined_df["local_path"].str.replace(
    r"\.\./data/images[\\/]", "", regex=True
)

In [122]:
combined_df

,title,description,final_description,skill_level,pattern_link,local_path
0,Quick n' Cozy Crochet Afghan,The Quick n' Cozy Crochet Afghan is the ultima...,Quick n' Cozy Crochet Afghan The Quick n' Cozy...,Beginner,https://www.allfreecrochet.com/Crochet-Afghan-...,Quick_n_Cozy_Crochet_Afghan.jpg
1,World's Easiest Afghan,If you've been searching for easy afghan patte...,World's Easiest Afghan If you've been searchin...,Beginner,https://www.allfreecrochet.com/Crochet-Afghan-...,Worlds_Easiest_Afghan.jpg
2,Ribbed Fingerless Gloves,"""These crochet ribbed fingerless gloves are ma...","Ribbed Fingerless Gloves ""These crochet ribbed...",Beginner,https://www.allfreecrochet.com/Gloves-and-Mitt...,Ribbed_Fingerless_Gloves.jpg
3,Chunky Adult Slippers,Learn how to crochet an adorable pair of Chunk...,Chunky Adult Slippers Learn how to crochet an ...,Beginner,https://www.allfreecrochet.com/Socks-and-Slipp...,Chunky_Adult_Slippers.jpg
4,Quick Little Bag,"""This Quick Little Bag is just that, and it ca...","Quick Little Bag ""This Quick Little Bag is jus...",Beginner,https://www.allfreecrochet.com/Crochet-Bag-Pat...,Quick_Little_Bag.jpg
...,...,...,...,...,...,...
2773,Premier Square Blanket Knit Pattern,Self-striping Premier Puzzle yarn creates a fu...,Premier Square Blanket Knit Pattern F01439 Sel...,NaN,https://herrschners.com/premier-square-blanket...,Premier_Square_Blanket_Knit_Pattern.jpg
2774,Premier Linen Stitch Blanket Knit Pattern,An easy-to-learn linen stitch creates a wonder...,Premier Linen Stitch Blanket Knit Pattern F014...,NaN,https://herrschners.com/premier-linen-stitch-b...,Premier_Linen_Stitch_Blanket_Knit_Pattern.jpg
2775,Lily Sugar 'n Cream Conversation Coasters,Serve up Valentine's drinks and treats with a ...,Lily Sugar 'n Cream Conversation Coasters Croc...,Beginner,https://herrschners.com/lily-sugar-n-cream-con...,Lily_Sugar_n_Cream_Conversation_Coasters.jpg
2776,Lily Sugar 'n Cream Lots of Love Dishcloth,Do daily chores with a little love using these...,Lily Sugar 'n Cream Lots of Love Dishcloth Cro...,Beginner,https://herrschners.com/lily-sugar-n-cream-lot...,Lily_Sugar_n_Cream_Lots_of_Love_Dishcloth.jpg
2777,Red Heart Valentine Scrubby,Scrub up in the kitchen or bath with a little ...,Red Heart Valentine Scrubby Crochet Beginner F...,Beginner,https://herrschners.com/red-heart-valentine-sc...,Red_Heart_Valentine_Scrubby.jpg

In [123]:
combined_df['skill_level'].value_counts()

skill_level
Beginner        1285
Intermediate     929
Advanced          63
Name: count, dtype: int64

In [124]:
combined_df['pattern_link'].nunique()

2766

In [125]:
combined_df = combined_df.drop_duplicates(subset=['pattern_link'], keep='first')

In [126]:
combined_df.loc[combined_df['description'].isna(),'pattern_link']
# dropping entry that no longer exists
combined_df = combined_df.loc[~combined_df['description'].isna()]

In [127]:
combined_df.to_csv("../src/all_patterns_combined.csv", index=False)