In [2]:
import pandas as pd
import os

In [3]:
all_free_df = pd.read_csv("../data/all_free_crochet_patterns.csv")
cols = ['title', 'description', 'skill_level', 'Crochet Hook', 'Yarn Weight', 'Finished Size']

all_free_df['final_description'] = (
    all_free_df[cols]
    .fillna('')
    .agg(' '.join, axis=1)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)
all_free_df.head()

all_free_df.rename(columns={'Crochet Hook': 'crochet_hook', 
'Yarn Weight': 'yarn_weight',
'Crochet Gauge': 'crochet_gauge',
'Finished Size': 'finished_size'}, inplace=True)
all_free_df.head()
# print(all_free_df.iloc[0,1])

,title,description,skill_level,crochet_hook,yarn_weight,img_url,local_path,pattern_link,crochet_gauge,finished_size,final_description
0,One Hour Spike Stitch Crochet Cowl,"If you have one spare hour in a day, you can m...",Easy,P/16 or 11.5 mm hook,(6) Super Bulky/Super Chunky (4-11 stitches fo...,https://irepo.primecp.com/2015/09/237913/spike...,../data/images\One_Hour_Spike_Stitch_Crochet_C...,https://www.allfreecrochet.com/Crocheted-Cowls...,NaN,NaN,One Hour Spike Stitch Crochet Cowl If you have...
1,47+ One Skein Crochet Patterns,We’ve all been there: you’re digging through y...,NaN,NaN,NaN,NaN,NaN,https://www.allfreecrochet.com/Miscellaneous-C...,NaN,NaN,47+ One Skein Crochet Patterns We’ve all been ...
2,World's Easiest Afghan,If you've been searching for easy afghan patte...,Beginner,H/8 or 5 mm hook,(4) Medium Weight/Worsted Weight and Aran (16-...,https://irepo.primecp.com/2014/12/204013/World...,../data/images\Worlds_Easiest_Afghan.jpg,https://www.allfreecrochet.com/Crochet-Afghan-...,"13 sc and 14 rows = 4"" (10cm)",Measurement: 48 x 60”,World's Easiest Afghan If you've been searchin...
3,Our Little Bunny,"""This is just a little bunny pattern I created...",Easy,E/4 or 3.5 mm hook,(4) Medium Weight/Worsted Weight and Aran (16-...,https://irepo.primecp.com/2017/12/357906/Our-L...,../data/images\Our_Little_Bunny.jpg,https://www.allfreecrochet.com/Crochet-Amiguru...,NaN,17 inches tall (including ears); 4 inches wide...,"Our Little Bunny ""This is just a little bunny ..."
4,Lazy Girl Crochet Blanket Pattern,Working up a crochet afghan has never been eas...,Easy,Q or 16mm hook,(6) Super Bulky/Super Chunky (4-11 stitches fo...,https://irepo.primecp.com/2015/07/229179/lazy-...,../data/images\Lazy_Girl_Crochet_Blanket_Patte...,https://www.allfreecrochet.com/Crochet-Afghan-...,2 V-sts = about 4 in. (10 cm) with 2 strands o...,NaN,Lazy Girl Crochet Blanket Pattern Working up a...

In [4]:
crochet_df = pd.read_csv("../data/crochet_crochet_patterns.csv")

# dropping this, has all nans
crochet_df = crochet_df.drop(columns=['Yarn Line', 'Yardage'])
description_col = crochet_df.columns[:-3]
print(description_col)

crochet_df['final_description'] = (
    crochet_df[description_col]
    .fillna('')
    .agg(' '.join, axis=1)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

crochet_df.rename(columns = {'Fiber Type': 'fiber_type', 'Pattern Type': 'pattern_type', 'Yarn Weight': 'yarn_weight', 
'Sizes Included': 'finished_size', 'Difficulty': 'skill_level', 'Needle / Hook Sizes': 'crochet_hook'}, 
inplace = True)

crochet_df.head()

Index(['title', 'description', 'Pattern Type', 'Difficulty', 'Sizes Included',
       'Yarn Weight', 'Fiber Type', 'Needle / Hook Sizes'],
      dtype='object')

,title,description,pattern_type,skill_level,finished_size,yarn_weight,fiber_type,crochet_hook,image_url,local_path,pattern_link,final_description
0,Wavy Chevron Dishclothby Jenny Konopinski,Save when you buy a project bundle! Striped or...,Crochet,Beginner,"Bright Colorway, Cabin Colorway, Candy Colorway",Worsted,Cotton,Size G (4.0mm) crochet hook,https://d2q9kw5vp0we94.cloudfront.net/i/_/big/...,../data/images\Wavy_Chevron_Dishclothby_Jenny_...,https://www.crochet.com/wavy-chevron-dishcloth...,Wavy Chevron Dishclothby Jenny Konopinski Save...
1,Filet Crochet Market Bagby Sara Dudek,Make a stunning market bag for trips to the fa...,Crochet,Intermediate,"27"" circumference, 15"" long",DK,Cotton,Size G (4.0mm) Crochet hook,https://d2q9kw5vp0we94.cloudfront.net/i/_/big/...,../data/images\Filet_Crochet_Market_Bagby_Sara...,https://www.crochet.com/filet-crochet-market-b...,Filet Crochet Market Bagby Sara Dudek Make a s...
2,Good Earth Blanketby Pattern Hut,Get cozy in color with a striped crochet blank...,Crochet,Easy,"35.75 x 48"" - spring picnic, 48.25 x 60"" - spr...",Worsted,Acrylic,US 7 (4.5mm) crochet hook,https://d2q9kw5vp0we94.cloudfront.net/i/_/big/...,../data/images\Good_Earth_Blanketby_Pattern_Hu...,https://www.crochet.com/good-earth-blanket/p/N...,Good Earth Blanketby Pattern Hut Get cozy in c...
3,Aberdeen Pulloverby Moon Elderidge,Bold and modern the geometric mosaic pattern o...,Crochet,Intermediate,"38.5"" finished chest, 42.75"" finished chest, 4...",Worsted,Acrylic,H/5.0mm & I/5.5mm crochet hooks,https://d2q9kw5vp0we94.cloudfront.net/i/_/big/...,../data/images\Aberdeen_Pulloverby_Moon_Elderi...,https://www.crochet.com/aberdeen-pullover/p/56291,Aberdeen Pulloverby Moon Elderidge Bold and mo...
4,Adventure Time Blanketby Amy Polcyn Niezur,Playful vehicles set off for adventure on this...,Crochet,Intermediate,"24"" Wide x 36"" Long",Fingering,Cotton,US D/3 (3.25mm) Crochet hook,https://d2q9kw5vp0we94.cloudfront.net/i/_/big/...,../data/images\Adventure_Time_Blanketby_Amy_Po...,https://www.crochet.com/adventure-time-blanket...,Adventure Time Blanketby Amy Polcyn Niezur Pla...

In [5]:
herrschners_df = pd.read_csv("../data/herrschners_crochet_patterns.csv")
herrschners_df = herrschners_df.drop(columns=['sku','upc', 'full_description'])
herrschners_df.head()
herrschners_df.rename(columns = {'product_link': 'pattern_link', 'skill': 'pattern_type', 
'difficulty': 'skill_level'}, inplace = True)
exclude_cols = ['pattern_link', 'review_count', 'image_url', 'local_path', 'star_rating', 'thread_size']
description_col = [col for col in herrschners_df.columns if col not in exclude_cols]
print(description_col)

herrschners_df['final_description'] = (
    herrschners_df[description_col]
    .fillna('')
    .agg(' '.join, axis=1)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)
herrschners_df.head()

['title', 'project_type', 'pattern_type', 'skill_level', 'merged_info', 'description', 'occasion', 'season', 'theme', 'fiber_content', 'yarn_weight']

,pattern_link,title,project_type,pattern_type,skill_level,merged_info,description,review_count,star_rating,image_url,local_path,occasion,season,theme,fiber_content,yarn_weight,thread_size,final_description
0,https://herrschners.com/herrschners-sunrise-st...,Herrschners Sunrise Stroll Tote,Tote,Crochet,Easy,F01730 Tote Crochet Easy,Accessorize in style with this textured two-to...,0,0,https://cdn11.bigcommerce.com/s-wgzqwlngdf/ima...,../data/images/Herrschners_Sunrise_Stroll_Tote...,NaN,NaN,NaN,NaN,NaN,NaN,Herrschners Sunrise Stroll Tote Tote Crochet E...
1,https://herrschners.com/village-yarn-blue-burs...,Village Yarn Blue Burst Pot Holders,Pot Holders,Crochet,Easy,F01729 Pot Holders Crochet Easy,Brighten your kitchen with a splash of color! ...,0,0,https://cdn11.bigcommerce.com/s-wgzqwlngdf/ima...,../data/images/Village_Yarn_Blue_Burst_Pot_Hol...,NaN,NaN,NaN,NaN,NaN,NaN,Village Yarn Blue Burst Pot Holders Pot Holder...
2,https://herrschners.com/willow-yarns-garden-so...,Willow Yarns Garden Song Shawlette,Shawl,Knit,Easy,F01728 Shawl Knit Easy,Be ready for backyard garden parties with this...,0,0,https://cdn11.bigcommerce.com/s-wgzqwlngdf/ima...,../data/images/Willow_Yarns_Garden_Song_Shawle...,NaN,NaN,NaN,NaN,NaN,NaN,Willow Yarns Garden Song Shawlette Shawl Knit ...
3,https://herrschners.com/herrschners-english-ga...,Herrschners English Garden Doily,Doily,Crochet,Easy,F01727 Doily Crochet Easy,No green thumb is needed to grow a garden of t...,0,0,https://cdn11.bigcommerce.com/s-wgzqwlngdf/ima...,../data/images/Herrschners_English_Garden_Doil...,NaN,NaN,NaN,NaN,NaN,NaN,Herrschners English Garden Doily Doily Crochet...
4,https://herrschners.com/herrschners-shamrock-g...,Herrschners Shamrock Glow Blanket,Blanket,Crochet,Easy,F01726 St. Patrick's Day Blanket Crochet Easy,It’s your lucky day! This free easy crochet bl...,0,0,https://cdn11.bigcommerce.com/s-wgzqwlngdf/ima...,../data/images/Herrschners_Shamrock_Glow_Blank...,St. Patrick's Day,NaN,NaN,NaN,NaN,NaN,Herrschners Shamrock Glow Blanket Blanket Croc...

In [7]:
lovecrafts_df = pd.read_csv("../data/lovecrafts_crochet_patterns.csv")
lovecrafts_df = lovecrafts_df.drop(columns = ['format', 'merged_info',
'techniques_and_construction', 'needles_required', 'crochet_thread_size'])
lovecrafts_df.head()

lovecrafts_df.rename(columns = {'product_link': 'pattern_link', 'craft': 'pattern_type'}, inplace = True)
exclude_cols = ['pattern_link', 'image_url', 'local_path']

lovecrafts_df['pages'] = lovecrafts_df['pages'].astype(str) + 'pages'
lovecrafts_df['number_of_patterns'] = lovecrafts_df['number_of_patterns'].astype(str) + 'patterns'

description_col = [col for col in lovecrafts_df.columns if col not in exclude_cols]
print(description_col)

lovecrafts_df['final_description'] = (
    lovecrafts_df[description_col]
    .fillna('')
    .agg(' '.join, axis=1)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)
lovecrafts_df.head()

['title', 'brand', 'pattern_type', 'designer', 'language', 'notes', 'number_of_patterns', 'pages', 'skill_level', 'yarn_weight', 'description', 'featured_product', 'crochet_hooks', 'finished_size']

,title,brand,pattern_type,designer,language,notes,number_of_patterns,pages,skill_level,yarn_weight,description,image_url,local_path,pattern_link,featured_product,crochet_hooks,finished_size,final_description
0,Jellyfish Babies,Independent Designer,Crochet,Jade Gauthier-Boutin,"English, French",• Two 6 mm safety eyes,1.0patterns,14.0pages,Beginner,Worsted,"With this pattern, you will be able to make as...",https://isv.prod.lovecrafts.co/v1/images/87236...,../data/images/Jellyfish_Babies.jpg,https://www.lovecrafts.com/en-us/p/jellyfish-b...,NaN,NaN,NaN,Jellyfish Babies Independent Designer Crochet ...
1,Sakura Market Bag,Independent Designer,Crochet,K.A.M.E. Crochet,"Dutch, English, French, German",NaN,1.0patterns,33.0pages,Intermediate,DK | Light Worsted,"NEW UPDATED VERSION CONTAINS DUTCH, FRENCH, GE...",https://isv.prod.lovecrafts.co/v1/images/cd77c...,../data/images/Sakura_Market_Bag.jpg,https://www.lovecrafts.com/en-us/p/sakura-mark...,Paintbox Yarns Cotton DK,NaN,NaN,Sakura Market Bag Independent Designer Crochet...
2,Easy Peasy Crochet Baby Blanket in Caron One P...,Caron,Crochet,NaN,English,NaN,1.0patterns,2.0pages,Beginner,AranSee Worsted Knitting PatternsSee Aran Croc...,Learn how to crochet with our beginners guide!,https://isv.prod.lovecrafts.co/v1/images/8a9cf...,../data/images/Easy_Peasy_Crochet_Baby_Blanket...,https://www.lovecrafts.com/en-us/p/easy-peasy-...,Caron One Pound,6.00mm (J),Blanket: 40in square,Easy Peasy Crochet Baby Blanket in Caron One P...
3,Baby Turtles,Independent Designer,Crochet,Jade Gauthier-Boutin,"English, French","• Two 6 mm safety eyes or buttons, beads, felt...",1.0patterns,12.0pages,Beginner,Worsted,"SKILLS REQUIRED Crocheting in spiral, magic ri...",https://isv.prod.lovecrafts.co/v1/images/c5cdb...,../data/images/Baby_Turtles.jpg,https://www.lovecrafts.com/en-us/p/baby-turtle...,NaN,NaN,NaN,Baby Turtles Independent Designer Crochet Jade...
4,Squishy Baby Octopus,Independent Designer,Crochet,Jade Gauthier-Boutin,"English, French",Two 12 mm safety eyes,1.0patterns,6.0pages,Beginner,Super Bulky,"With this pattern, you will be able to make as...",https://isv.prod.lovecrafts.co/v1/images/95d72...,../data/images/Squishy_Baby_Octopus.jpg,https://www.lovecrafts.com/en-us/p/squishy-bab...,NaN,NaN,NaN,Squishy Baby Octopus Independent Designer Croc...

In [8]:
lovecrafts_df.isna().sum()

title                    3
brand                    3
pattern_type             3
designer              2589
language                 3
notes                 6567
number_of_patterns       0
pages                    0
skill_level            600
yarn_weight           1197
description              3
image_url                3
local_path               3
pattern_link             0
featured_product      5772
crochet_hooks         7562
finished_size         7165
final_description        0
dtype: int64

In [9]:
features = ['title', 'description', 'final_description', 'skill_level', 'pattern_link', 'local_path']

In [10]:
combined_df = pd.concat(
    [
        all_free_df[features],
        crochet_df[features],
        lovecrafts_df[features],
        herrschners_df[features]
    ],
    axis=0,
    ignore_index=True
)

combined_df.shape

(10954, 6)

In [11]:
combined_df["local_path"] = combined_df["local_path"].str.replace(
    r"\.\./data/images[\\/]", "", regex=True
)

In [13]:
combined_df["local_path"].isna().sum()

np.int64(4)

In [14]:
combined_df = combined_df[~combined_df['local_path'].isna()]

In [16]:
combined_df.to_csv("../src/all_patterns_combined.csv", index=False)